// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrfMj0MXZc959yT5nO62ld44r6l-e5AFU',
    appId: '1:331589088407:android:a003dd0e8d1147c434a5d2',
    messagingSenderId: '331589088407',
    projectId: 'aethar-6826b',
    storageBucket: 'aethar-6826b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCl8cJGfV2cfHSyrZOFWQWflKF35N_VguQ',
    appId: '1:331589088407:ios:db5b92fec44cc2ab34a5d2',
    messagingSenderId: '331589088407',
    projectId: 'aethar-6826b',
    storageBucket: 'aethar-6826b.appspot.com',
    iosClientId: '331589088407-aivu49j9ru4beu2oofjlo5063c8s0gno.apps.googleusercontent.com',
    iosBundleId: 'com.aethar.app',
  );
}
